---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mastodon.fullname" . }}-system
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.system.accessMode }}
  resources:
    {{- toYaml .Values.persistence.system.resources | nindent 4}}
  storageClassName: {{ .Values.persistence.system.storageClassName }}
